version: '3'
services:
  datacollection_service:
    build: ./datacollection_service
    volumes:
      - ./datacollection_service:/datacollection_service
  sentiment_service:
    build: ./sentiment_service
    depends_on:
      - datastore
      - datacollection_service
    environment:
      serverAddr: datacollection_service:5253
      datastoreAddr: datastore:27017
  frontend:
    build: ./frontend
    depends_on:
      - sentiment_service
    ports:
      - 3000:3000
    environment:
      DATASTORE_ADDR: datastore:27017
    
  datastore:
    image: mongo
    ports:
      - 27017:27017

