apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: sentiment-service
  name: sentiment-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sentiment-service
    spec:
      containers:
      - env:
        - name: datastoreAddr
          value: datastore:27017
        - name: serverAddr
          value: datacollection_service:5253
        image: sentiment-service
        name: sentiment-service
        resources: {}
      restartPolicy: Always
status: {}
