// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twitter_route.proto

/*
Package twitter_route is a generated protocol buffer package.

It is generated from these files:
	twitter_route.proto

It has these top-level messages:
	Params
	Tweet
*/
package twitter_route

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Params struct {
	Track         []string `protobuf:"bytes,1,rep,name=Track" json:"Track,omitempty"`
	Language      []string `protobuf:"bytes,2,rep,name=Language" json:"Language,omitempty"`
	StallWarnings bool     `protobuf:"varint,3,opt,name=StallWarnings" json:"StallWarnings,omitempty"`
}

func (m *Params) Reset()                    { *m = Params{} }
func (m *Params) String() string            { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()               {}
func (*Params) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Params) GetTrack() []string {
	if m != nil {
		return m.Track
	}
	return nil
}

func (m *Params) GetLanguage() []string {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *Params) GetStallWarnings() bool {
	if m != nil {
		return m.StallWarnings
	}
	return false
}

type Tweet struct {
	CreatedAt    string `protobuf:"bytes,1,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
	RetweetCount int64  `protobuf:"varint,2,opt,name=RetweetCount" json:"RetweetCount,omitempty"`
	Text         string `protobuf:"bytes,3,opt,name=Text" json:"Text,omitempty"`
}

func (m *Tweet) Reset()                    { *m = Tweet{} }
func (m *Tweet) String() string            { return proto.CompactTextString(m) }
func (*Tweet) ProtoMessage()               {}
func (*Tweet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Tweet) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Tweet) GetRetweetCount() int64 {
	if m != nil {
		return m.RetweetCount
	}
	return 0
}

func (m *Tweet) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "Params")
	proto.RegisterType((*Tweet)(nil), "Tweet")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TwitterRoute service

type TwitterRouteClient interface {
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	GetTweets(ctx context.Context, in *Params, opts ...grpc.CallOption) (TwitterRoute_GetTweetsClient, error)
}

type twitterRouteClient struct {
	cc *grpc.ClientConn
}

func NewTwitterRouteClient(cc *grpc.ClientConn) TwitterRouteClient {
	return &twitterRouteClient{cc}
}

func (c *twitterRouteClient) GetTweets(ctx context.Context, in *Params, opts ...grpc.CallOption) (TwitterRoute_GetTweetsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TwitterRoute_serviceDesc.Streams[0], c.cc, "/TwitterRoute/GetTweets", opts...)
	if err != nil {
		return nil, err
	}
	x := &twitterRouteGetTweetsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TwitterRoute_GetTweetsClient interface {
	Recv() (*Tweet, error)
	grpc.ClientStream
}

type twitterRouteGetTweetsClient struct {
	grpc.ClientStream
}

func (x *twitterRouteGetTweetsClient) Recv() (*Tweet, error) {
	m := new(Tweet)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TwitterRoute service

type TwitterRouteServer interface {
	// Obtains the Features available within the given Rectangle.  Results are
	// streamed rather than returned at once (e.g. in a response message with a
	// repeated field), as the rectangle may cover a large area and contain a
	// huge number of features.
	GetTweets(*Params, TwitterRoute_GetTweetsServer) error
}

func RegisterTwitterRouteServer(s *grpc.Server, srv TwitterRouteServer) {
	s.RegisterService(&_TwitterRoute_serviceDesc, srv)
}

func _TwitterRoute_GetTweets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Params)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TwitterRouteServer).GetTweets(m, &twitterRouteGetTweetsServer{stream})
}

type TwitterRoute_GetTweetsServer interface {
	Send(*Tweet) error
	grpc.ServerStream
}

type twitterRouteGetTweetsServer struct {
	grpc.ServerStream
}

func (x *twitterRouteGetTweetsServer) Send(m *Tweet) error {
	return x.ServerStream.SendMsg(m)
}

var _TwitterRoute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TwitterRoute",
	HandlerType: (*TwitterRouteServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTweets",
			Handler:       _TwitterRoute_GetTweets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "twitter_route.proto",
}

func init() { proto.RegisterFile("twitter_route.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x4d, 0xd7, 0xae, 0xcd, 0x50, 0x2f, 0xa3, 0x87, 0x50, 0x3c, 0x84, 0xc5, 0x43, 0x4e,
	0x4b, 0xd1, 0x5f, 0x20, 0x3d, 0x78, 0xf1, 0x20, 0x31, 0xe0, 0x49, 0x74, 0xd4, 0x61, 0x29, 0xd6,
	0x44, 0xb2, 0xb3, 0xd4, 0x9f, 0x2f, 0xcd, 0x82, 0x65, 0x6f, 0xf3, 0xbe, 0x79, 0xf0, 0xf8, 0xe0,
	0x42, 0xf6, 0x5b, 0x11, 0xce, 0xaf, 0x39, 0x0d, 0xc2, 0xed, 0x4f, 0x4e, 0x92, 0x9a, 0x37, 0xa8,
	0x1f, 0x29, 0xd3, 0x77, 0x8f, 0x97, 0x30, 0x0f, 0x99, 0x3e, 0xbe, 0x8c, 0xb2, 0x95, 0xd3, 0x7e,
	0x0c, 0xb8, 0x82, 0xc5, 0x03, 0xc5, 0x6e, 0xa0, 0x8e, 0xcd, 0xac, 0x3c, 0xfe, 0x33, 0x5e, 0xc3,
	0xf9, 0x93, 0xd0, 0x6e, 0xf7, 0x4c, 0x39, 0x6e, 0x63, 0xd7, 0x9b, 0xca, 0x2a, 0xb7, 0xf0, 0x53,
	0xd8, 0xbc, 0xc0, 0x3c, 0xec, 0x99, 0x05, 0xaf, 0x40, 0x6f, 0x32, 0x93, 0xf0, 0xe7, 0x9d, 0x18,
	0x65, 0x95, 0xd3, 0xfe, 0x08, 0xb0, 0x81, 0xa5, 0x67, 0x39, 0x14, 0x37, 0x69, 0x88, 0x62, 0x66,
	0x56, 0xb9, 0xca, 0x4f, 0x18, 0x22, 0x9c, 0x06, 0xfe, 0x95, 0xb2, 0xa3, 0x7d, 0xb9, 0x6f, 0xd6,
	0xb0, 0x0c, 0xa3, 0x97, 0x3f, 0x68, 0xa1, 0x05, 0x7d, 0xcf, 0x52, 0x16, 0x7b, 0x3c, 0x6b, 0x47,
	0xb9, 0x55, 0xdd, 0x16, 0xd2, 0x9c, 0xac, 0xd5, 0x7b, 0x5d, 0xcc, 0x6f, 0xff, 0x02, 0x00, 0x00,
	0xff, 0xff, 0xdd, 0x5e, 0xf0, 0x96, 0x10, 0x01, 0x00, 0x00,
}
